logging:
  level:
    root: info

  file:
    path: /log
  config: classpath:config/logback.xml

spring:
    redis:
      host: localhost
      password: 123456

    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml

rocketmq:
  name-server: localhost:9876
